### ISSUE TITLE
Request: Barebones sample app

### ISSUE THREAD

**Issue by kevin-ashton** [mrsum/webpack-svgstore-plugin#101]
Is there a barebones sample app someplace? I'm having trouble getting it to build a sprite.svg even after going through the documentation. I'm sure it's some small little thing I'm doing wrong but it would be nice if there was a simple working app I could start from.

**Comment by mrsum** [comment]
@kevin-ashton look here plz https://github.com/mrsum/webpack-svgstore-plugin/tree/develop/platform
