### ISSUE TITLE
Async loading svg sprite won't work on IE9 because of XDomainRequest

### ISSUE THREAD

**Issue by kazagkazag** [mrsum/webpack-svgstore-plugin#103]
There is a block of code in `svgxhr.js`...
````
if (typeof XDomainRequest !== 'undefined') {
    _ajax = new XDomainRequest();
}
````
With that in source code my icons won't load in IE9 and IE10. `_ajax.onerror` throws error but there is no error message, so I don't know why it doesn't work. 
**But! When I commented this out, icons appeared!** IE9 can use XMLHttpRequest as well.

As far as I know, XDomainRequest is some kind of sub-standard introduced by MS years ago. Do you really need that in this file? It seems, that it brokes loading SVG on old IE...

Any help, guys?

I use nginx to server my files and I run IE9 on VirtualBox (I work on Ubuntu 16.04), if that matters.

**Comment by mrsum** [comment]
@kazagkazag Hello. 
You can override loader function into your project. 

BTW. copy ajax helper svgxhr.js file.

**Comment by alexiscordova** [comment]
Looks like there may have been a regression for this. In version 4.0.0, the XDomainRequest type check block has returned, and I can confirm it causes the XHR to fail—causing the SVGs to not display—in at least IE 10. Commenting this block out displays the SVGs as expected.
