### ISSUE TITLE
Add example for use

### ISSUE THREAD

**Issue by khmelevskii** [mrsum/webpack-svgstore-plugin#105]

**Comment by eilinora** [comment]
This would be greatly helpful! The documentation is sparse and with the change between 2.0 and now 3.0 it's hard to know what exactly needs to be done get the plugin working again. Better documentation an example would be helpful.

**Comment by mrsum** [comment]
@khmelevskii @eilinora can you look up to https://github.com/mrsum/webpack-svgstore-plugin/tree/develop/platform this folder. 

I think this example is enough

**Comment by mrsum** [comment]
@khmelevskii @eilinora Made new README.md here 
https://github.com/mrsum/webpack-svgstore-plugin/blob/feature/long-term-caching/README.md
