### ISSUE TITLE
Use environment variables in path

### ISSUE THREAD

**Issue by iamrane** [mrsum/webpack-svgstore-plugin#122]
Hi!
It seems to be something wrong when i use environment variables in my path value.
I guess its the order that webpack do things.

From my understanding webpack replaces the env. variable on build, but it seems to me that __svg__ magick is happening before this?

My code looks like

```
const __svg__ = { path: `./assets/${ process.env.BRAND }/*.svg`, name: 'assets/sprite-[hash].svg' };
require('webpack-svgstore-plugin/src/helpers/svgxhr')(__svg__);
```

and plugins in config

```
new SvgStore({prefix: 'icon-'})
```

**Comment by mrsum** [comment]
@iamrane think that ```const``` isn't parsed cause when plugin was wrote, ```let/const``` not support

**Comment by iamrane** [comment]
I changed to var. Still not working. Its just stops at "90% optimize assets" when i start webpack.
If i hard code the value of a variable and try to use it, it still doesn't work. I guess its somehow how the __svg__ magic is being used.

```
var __svg__ = { path: '../../../styles/mybrand/images/svg-icons/**/*.svg', name: '[hash].icons.svg' };
require('webpack-svgstore-plugin/src/helpers/svgxhr')(__svg__);
```
works fine but not
```
var brand = 'mybrand';
var __svg__ = { path: '../../../styles/' + brand + '/images/svg-icons/**/*.svg', name: '[hash].icons.svg' };
require('webpack-svgstore-plugin/src/helpers/svgxhr')(__svg__);
```

**Comment by iamrane** [comment]
I made it work.
if (process.env.BRAND === 'mybrand') {
   var __svg__ = { path: '../../../styles/mybrand/images/svg-icons/**/*.svg', name: '[hash].icons.svg' };
}
if (process.env.BRAND === 'myotherbrand') {
   var __svg__ = { path: '../../../styles/myotherbrand/images/svg-icons/**/*.svg', name: '[hash].icons.svg' };
}
require('webpack-svgstore-plugin/src/helpers/svgxhr')(__svg__);
