### ISSUE TITLE
Render wrong color + shape of SVG icons

### ISSUE THREAD

**Issue by SLyHuy** [mrsum/webpack-svgstore-plugin#124]
Render wrong color + shape of SVG icons
Same issue here: https://github.com/kisenka/svg-sprite-loader/issues/74
But this one is wrong in shape too.

![screen shot 2017-01-23 at 12 35 32](https://cloud.githubusercontent.com/assets/1643397/22192678/8f79e46c-e168-11e6-8e3c-e4bf9c56d7a7.png)

My node version: v6.9.4

**Comment by restrry** [comment]
I could be wrong, but seems like result of svgo minification. probably, svgo processing should be optional

**Comment by mrsum** [comment]
@SLyHuy look up to
```
new SvgStore({
      // svgo options
      svgoOptions: {
        plugins: [
          { removeTitle: true }
        ]
      },
      prefix: 'icon'
})
```

doc available here https://github.com/svg/svgo
