### ISSUE TITLE
Specific instantiate options 

### ISSUE THREAD

**Issue by balazswmann** [mrsum/webpack-svgstore-plugin#128]
Is is possible to provide specific instantiate options like class or id attributes for the svg element? Maybe I just don't see my mistake, but the snippet below doesn't work fork for me:

`
var __svg__ = {
  path: '...',
  name: '...',
  svg: {
    id: 'myid',
    class: 'myclass'
  }
};
`

**Comment by lgordey** [comment]
Nope
