### ISSUE TITLE
change the ajax path request?

### ISSUE THREAD

**Issue by webmarkelov** [mrsum/webpack-svgstore-plugin#135]
Hi! How change the ajax path request?
```
webpack 2.1.0
webpack-svgstore-plugin 4.0.0
```
my solution:
```javascript
// app.js
const __svg__  = { path: './../img/svg/**/*.svg', name: 'svg/[hash].sprite.svg' };
  require('webpack-svgstore-plugin/src/helpers/svgxhr')({ filename: `app/dist/${__svg__.filename }`});
```
maybe there's an even better option ?

**Comment by AndreKelling** [comment]
saved my day! found no better option.

doing it with path's like:
`
new SvgStore(path.join(__dirname + '/src', 'icons', '**/*.svg'), path.join('assets', 'svg'), {
      name: '[hash].sprite.svg',
      prefix: 'myprefix-',
      svgoOptions: {
        // options for svgo, optional
      }
    })
`
wasn't somehow not working for me.
