### ISSUE TITLE
Code samples should show how to get plugin working in webpack

### ISSUE THREAD

**Issue by georgeadamson** [mrsum/webpack-svgstore-plugin#14]
Please could you elaborate on the Code Samples to show what else needs to be added to a project to build and make use of the resulting sprite file?
Where does the sprite file end up? How would you bundle it into the page?
The Plugin code is clearly illustrated but is more needed, such as defining a Loader?
Many thanks

**Comment by georgeadamson** [comment]
Partly solved: It works in prod but not in dev-server because it relies on creating an actual file.

**Comment by lgordey** [comment]
@georgeadamson Thank you for feedback!
I'll add code samples soon, please follow the changes.

**Comment by mrsum** [comment]
@georgeadamson as you know, webpack-dev-server using RAM for static provide. 
And you can get file via webpack:// protocol.

I recommend using this loader at once time, when you want to create sprite and put them to HDD.
