### ISSUE TITLE
v4.0.2: DOMContentLoaded does not working

### ISSUE THREAD

**Issue by sectsect** [mrsum/webpack-svgstore-plugin#162]
`DOMContentLoaded` added in v4.0.2 seems like does not fired. https://github.com/mrsum/webpack-svgstore-plugin/commit/e05eef676e6e1a1de8c46166450f5a75493cffd2

Thanks.

**Comment by lgordey** [comment]
@melloc01 pls, check this out

**Comment by melloc01** [comment]
Hey @lgordey, added a helper function & used it on svgxhr:
ref: https://www.sitepoint.com/jquery-document-ready-plain-javascript/

May you try my branch and check whether it fixes your issue @sectsect ?

Travis is failing, I'm commuting right now, will check as soon as I get home

**Comment by sectsect** [comment]
@melloc01 

Thanks for your PR https://github.com/mrsum/webpack-svgstore-plugin/pull/163

I tried your branch `fix/dom-access` on my environment.
It seems that the problem has been solved.
Great work :tada:

**Comment by melloc01** [comment]
cool @sectsect :)
friendly ping @lgordey

**Comment by lgordey** [comment]
@melloc01 @sectsect 
Check **4.0.3**  😉
