### ISSUE TITLE
svgxhr.js

### ISSUE THREAD

**Issue by cjroebuck** [mrsum/webpack-svgstore-plugin#17]
Got the svg sprite generated and I can see it served on webpack dev server. 

But how do I configure svgxhr.js to load the sprite dynamically (using the unique hash). I don't understand where this gets served from?

from README:

### 2. Include svgxhr.js into your webpage
     <script src="/assets/svgxhr.js" type="text/javascript" charset="utf-8"></script>

This step just isn't working for me.

**Comment by mrsum** [comment]
@cjroebuck Hello!

We are prepare new version v2.0.4 into npmjs

Take a look next config:

```javascript
var SvgStore = require('webpack-svgstore-plugin');

module.exports = {
  entry: {
    app: path.join(_path, 'platform', 'static', 'js', 'index.js'),
  },
  plugins: [
    new SvgStore(path.join(sourcePath, 'svg'), path.join(distPath, 'svg'), {
      name: 'svg/[hash].sprite.svg',
      chunk: 'app'
    })
  ]
}
```
If thats will be work, please close this issue

Best regards.

**Comment by mrsum** [comment]
@cjroebuck what about?
