### ISSUE TITLE
viewBox attribute is case sensitive

### ISSUE THREAD

**Issue by jzempel** [mrsum/webpack-svgstore-plugin#37]
https://github.com/mrsum/webpack-svgstore-plugin/blob/develop/helpers/utils.js#L131 should be

```js
viewBox: dom.attribs.viewbox
```

http://www.w3.org/TR/SVG/styling.html#CaseSensitivity

**Comment by mrsum** [comment]
@jzempel the problem inside middleware which transform all svg attributes to small case. I mean what happens if destination sprite will contain element with small case attirbs?

**Comment by jzempel** [comment]
If you don't change the line as shown above, viewBox is lowercase and the sprited SVG symbols don't render to the correct size when they are referenced. I was able to make the plugin work as expected by hacking the case change on ```viewBox: dom.attribs.viewbox```.

**Comment by mrsum** [comment]
@jzempel thanks for report! Next release will contain this fix

**Comment by XOP** [comment]
@jzempel oh my god, thanks! wasted so much time on this stupid bug :( 
thanks for pointing this out! better be fixed ASAP, this kills all scaling

**Comment by lgordey** [comment]
Fixed. Try 2.1.2 version.

**Comment by XOP** [comment]
@lgordey that does it, thanks!
