### ISSUE TITLE
relative path to svg sprite

### ISSUE THREAD

**Issue by chicoxyzzy** [mrsum/webpack-svgstore-plugin#38]
I have app which is embedded into page for some path let's say http://some.domain.com/blablabla/app.
When I use `webpack-svgstore-plugin` it creates `svgXHR` which is relative to `some.domain.com` (and possibly port), i.e. http://some.domain.com/images/sprite.svg. Is there any way to make it relative to `path` part of location (i.e. http://some.domain.com/blablabla/app/images/sprite.svg)? If no, I think it should be easy to implement by adding `location.pathname` [here](https://github.com/mrsum/webpack-svgstore-plugin/blob/develop/helpers/svgxhr.js#L15) based on some option.

**Comment by lgordey** [comment]
@chicoxyzzy 
I think it's not correct to use `pathname` here.
Maybe you can do it with [`baseURL`](https://github.com/mrsum/webpack-svgstore-plugin/pull/28) option?

**Comment by chicoxyzzy** [comment]
`baseUrl` is static and it works in build time only. That means that if you'll change path from http://some.domain.com/blablabla/app to http://some.domain.com/newpath/app app will be broken. The idea is to keep path relative to some custom root.

**Comment by mrsum** [comment]
in 3.0.0-beta all paths is relative by publicPath. 

for example, if your publicPath is /var/first/folder/ and you using

```javascript
var __svg__ = { path: './assets/svg/**/*.svg', name: 'assets/svg/[hash].logos.svg' };
```

sprite will compile to /var/first/folder/assets/svg/
