### ISSUE TITLE
Feature request: exclude option

### ISSUE THREAD

**Issue by chicoxyzzy** [mrsum/webpack-svgstore-plugin#39]
exclude option (with same behavior as in loaders) will be useful in some cases

**Comment by lgordey** [comment]
@chicoxyzzy can you make an example of such case?

**Comment by chicoxyzzy** [comment]
Sure.
Lets say we have such file tree:
```
/svg
  /logos
    apple.svg
    google.svg
  other.svg
  stuff.svg
```
Logos should be placed in background so they should be in styles not svg sprite. By the way there is no way to not include them into sprite with file tree above. So excluding `/logos` via `exclude` option which works as lwebpack loaders' `exclude` (for convenience) or if plugin will be able to take an array as first argument (as it already uses `glob`) to use patterns like `!/logos/**/*.svg` will be very handy.

**Comment by lgordey** [comment]
In this case you can easily fix it with structure changes.

For example, you can make the structure as:
```
/svg
  /logos
    apple.svg
    google.svg
  /sprite
    other.svg
    stuff.svg
```
So in plugin you will use pattern like `'svg/sprite/**/*.svg'`.

**Comment by lgordey** [comment]
@chicoxyzzy Because you still have to change the structure of your svg's to write the correct exclude pattern for glob.

**Comment by chicoxyzzy** [comment]
@lgordey sure I can but only if I am _owner_ of these files and they are not in 3rd-party npm module

**Comment by chicoxyzzy** [comment]
> Because you still have to change the structure of your svg's to write the correct exclude pattern for glob.

not necessarily

**Comment by mrsum** [comment]
@chicoxyzzy you right. we aplly this issue and will make it at next release

**Comment by lgordey** [comment]
@chicoxyzzy check https://github.com/mrsum/webpack-svgstore-plugin/pull/65
