### ISSUE TITLE
Wrong link if I'm using webpack-dev-server

### ISSUE THREAD

**Issue by limpbrains** [mrsum/webpack-svgstore-plugin#42]
I'm running webpack-dev-server, it serves static files on `http://localhost:2992/` 
Inside my http://localhost:2992/_assets/entry.js I have 
`document.addEventListener('DOMContentLoaded', svgXHR('http:/127.0.0.1:2992/_assets/build/public/svg/9fea4835cba8c510fb69ca3c6e161ec1.sprite.svg'), false);
`

`http:/127.0.0.1:2992` is wrong, should be `http://127.0.0.1:2992`

**Comment by limpbrains** [comment]
`baseUrl` on set

**Comment by mrsum** [comment]
@limpbrains Thank you for report. I have one question is how can i get this bug? Do you have some repo for testing?

**Comment by limpbrains** [comment]
@mrsum take a look at https://github.com/limpbrains/react-starter, I've added SvgStore to make-webpack-config.js
use `npm run hot-dev-server` to launch webpack, and then open `http://localhost:2992/_assets/main.js`

**Comment by lgordey** [comment]
@limpbrains Try 2.1.3 version

**Comment by janhoogeveen** [comment]
@limpbrains After checking our your fork of react-starter, I don't think you solved the issue. You can see if you open the page that it makes a request for http://localhost:8080/http://localhost:2992/_assets/svg/60ef7de3fa5632941b24ab62eb608009.sprite.svg
