### ISSUE TITLE
IE10 problem with svg sprite upload

### ISSUE THREAD

**Issue by fr-ench** [mrsum/webpack-svgstore-plugin#46]
When plugin is used with "chunk" option, then _ajax.onload callback from Svgxhr.js sometimes doesn't fire in the resulting chunk. I believe the reason is _ajax.send(); should be called after _ajax.onload is attached. 
This happens always when used with webpack-dev-server (I proxy my local website to localhost:8080  and my Access-Control-Allow-Origin headers are set correctly).

Also would be great to have an option to use only XMLHttpRequest even if XDomainRequest  is supported (why not, if the files are stored locally).

**Comment by lgordey** [comment]
> I believe the reason is _ajax.send(); should be called after _ajax.onload is attached. 
I guess you're right.
We will fix it in next release.

**Comment by dmitrif** [comment]
https://github.com/mrsum/webpack-svgstore-plugin/pull/53

**Comment by lgordey** [comment]
@dmitrif @fr-ench 
Please try 2.1.3 version
