### ISSUE TITLE
extract-text-webpack-plugin compatibility

### ISSUE THREAD

**Issue by restrry** [mrsum/webpack-svgstore-plugin#54]
Hi, guys! I noticed, that after adding svgstore-plugin build time in my project increased from 9sec. to 29sec. It seems that the root of problem that plugin uses `compilation` event [here](https://github.com/mrsum/webpack-svgstore-plugin/blob/develop/index.js#L87)
But if you use `extract-text-webpack-plugin` in your project this events will fire several times and it leads to multiple run `svgstore-plugin`
How can we fix this problem? use 'emit' event (it works for me, btw)? add caching?
[demo repo](https://github.com/restrry/svgstore-demo-problem)

**Comment by lgordey** [comment]
@restrry Hi!
Unfortunately, we can't use `emit`, because we need access to `optimize-chunk-assets` state which is only in `Compilation` instance.
So yes, I think we need something like caching.

**Comment by lgordey** [comment]
@restrry Thanks for PR. 👍 Use 2.2.0 version.
