### ISSUE TITLE
Combine with Webpack Dev Server

### ISSUE THREAD

**Issue by janhoogeveen** [mrsum/webpack-svgstore-plugin#62]
How would you combine this package with Webpack Dev Server?

My webpack-dev-server is running on port 3001.
My public app is running on port 3000.

My Publicpath is configured to a host + port so the Ajax request to the file looks like http://localhost:3000/http://localhost:3001/dist/icons/sprite.svg 

I can rewrite basePath to http://localhost:3001 but then you get a request to http://localhost:3001/http://localhost:3001/dist/icons/sprite.svg 

When I run a build in production mode manually (no webpack-dev-server) the publicPath is set to 'dist' and everyhing works okay.

Maybe the package could accept an override function so the publicPath does not automatically get injected into the url string?

**Comment by mrsum** [comment]
Hello! We can't realised this feature, cause svg concatenation action is really high CPU level action.
But i think about this feature.

**Comment by lgordey** [comment]
@janhoogeveen Hi!
Try 2.1.4 plugin version.

**Comment by janhoogeveen** [comment]
Hi @lgordey, I'll give it a go as soon as I can test this. Thanks for the headsup!
Any specific configuration I need to be aware of?

**Comment by lgordey** [comment]
I think no.
Unfortunately sprite will not be recreated automatically, but must work in development mode with correct paths by default.

**Comment by lgordey** [comment]
@janhoogeveen Hi! Check 2.2.0 version
