### ISSUE TITLE
Using svgoOptions

### ISSUE THREAD

**Issue by ehinter** [mrsum/webpack-svgstore-plugin#63]
Hi, can you add some documentation on the proper way to use svgoOptions? I'm currently using it like this:

`svgoOptions: {
    removeTitle: false,
    removeUselessStrokeAndFill: true
}`

But it doesn't seem to do anything. Is this the correct way to use the options?

Thanks!

**Comment by mdopieralski** [comment]
+1

**Comment by fobdy** [comment]
as i saw the source svgo wasnt supported

**Comment by lgordey** [comment]
@ehinter @mdopieralski @fobdy 
You can use your custom config for SVGO like this:
```javascript
svgoOptions: {
  plugins: [
    {removeTitle: true},
    {removeUselessStrokeAndFill: true}
  ]
}
```
I will add this to README in next release.

**Comment by lgordey** [comment]
@ehinter 
But I'm afraid that in the current architecture title is removed by the plugin by default.

**Comment by DavidWells** [comment]
I'm also having issues with this.

It would appear that changing any of the SVGO options has no effect on the final sprite.

What is the correct format for changing options more complex config options?

This code causes the build to fail silently and no sprite is generated
```
 new SvgStore(path.join(sourcePath, '**/*.svg'), path.join('svg'), {
      svg: {
        xmlns: 'http://www.w3.org/2000/svg',
        style: 'position:absolute; width: 0; height: 0'
      },
      name: 'sprite.svg',
      chunk: 'index',
      prefix: '',
      svgoOptions: {
        plugins: [{
          transformsWithOnePath: {
            width: 200,
            height: 100,
            scale: 10
          }
        }]
      }
    })
```

**Comment by DavidWells** [comment]
How can I change the precision option for example https://github.com/svg/svgo#how-to-use?

Thanks!

**Comment by justo** [comment]
> But I'm afraid that in the current architecture title is removed by the plugin by default.
That is bummer, I spent a while trying to figure out why my titles were being removed.
