### ISSUE TITLE
Case sensitivity for symbol: {viewBox: { } }

### ISSUE THREAD

**Issue by MikeW90** [mrsum/webpack-svgstore-plugin#68]
When I try to set symbol: {viewBox: '0 0 100 100'}  in the SvgStore options, no changes occur with the symbol's viewBox attribute. If, however, I edit helpers/utils.js such that viewBox: dom.attribs.viewBox  is changed to viewBox: dom.attribs.viewbox (removing the capitalization) the problem goes away. Is this an issue that can be resolved in a subsequent release? And does there currently exist some kind of workaround that doesn't involve changing the package or the utils helper file?

Thank you!

**Comment by lgordey** [comment]
@MikeW90 Hi!
That's not correct.
We will lose `viewBox` parameters of each svg separately if remove capitalization.

In fact, in the settings you specify a `viewBox` for a sprite (if you need it), and not for a particular symbol.
And code like:
```javascript
svg: {
  viewBox: '0 0 100 100'
},
```
works for me (as sprite viewBox attribute).

So I do not really understand your problem.
Can you give an example?

**Comment by lgordey** [comment]
@MikeW90 I suppose the problem is no longer relevant
