### ISSUE TITLE
require svgxhr function from webpack-svgstore-plugin

### ISSUE THREAD

**Issue by DragorWW** [mrsum/webpack-svgstore-plugin#70]
if webpack in watch mode or use webpack-dev-server this plugin not add svgxhr to chunk.

I suggest rewrite svgxhr.js to commonJs style. So I could require in my code.
```
var svgxhr = require('webpack-svgstore-plugin/helpers/svgxhr.js');
svgxhr('/build/sprite.svg');
```

**Comment by mrsum** [comment]
Cool! I want to include this method at new release!

**Comment by mrsum** [comment]
@DragorWW Hi bud! Thx for your advice, i'am refactor plugin and you can test it in 3.0.0-beta version
