### ISSUE TITLE
Support in webpack2

### ISSUE THREAD

**Issue by Krisa** [mrsum/webpack-svgstore-plugin#71]
As ConcatSource is not part of Webpack2, this fails when the plugin is trying to resolve `webpack/lib/ConcatSource`.

**Comment by mrsum** [comment]
Hi @Krisa we are didn't decide yet for maintain this package at webpack v2 cause right now it's beta and production not ready.

**Comment by lgordey** [comment]
Fixed by https://github.com/mrsum/webpack-svgstore-plugin/pull/81
