### ISSUE TITLE
Webpack Dev Server doesn't bundle sprite.svg on recompile

### ISSUE THREAD

**Issue by feedm3** [mrsum/webpack-svgstore-plugin#73]
When I start the webpack dev server everything works fine on the inital startup. All svg's get bundled correctly and I can use them in my app. But after I do a codechange and therefore trigger a recompile, the sprite.svg file doesn't get bundled and all svg icons are gone.

I initialize the SVG Store as following:
```javascript
plugins.push(new SvgStore(
    path.join(__dirname, '/public/assets', '**/*.svg'), // input path
    '', // output path
    {
        name: '[hash].sprite.svg',
        chunk: 'main',
        prefix: '',
        svgoOptions: {}
    }
));
```

**Comment by AlexYankee** [comment]
+1 same here

**Comment by eilinora** [comment]
same as well

**Comment by AlexYankee** [comment]
@feedm3, @eilinora - here is my fork having this issue fixed https://github.com/AlexYankee/webpack-svgstore-plugin (with files caching integrated as well from https://github.com/restrry/webpack-svgstore-plugin)

**Comment by eilinora** [comment]
@AlexYankee excellent! I was just starting to investigate the issue, are you going to PR against the mrsum's or maintain this as a separate fork?

**Comment by lgordey** [comment]
I'll take a look on all issues and pr's on the weekend.
New version will be released within three days.

Thanks for feedback.

**Comment by lgordey** [comment]
@AlexYankee you can make PR without cache fixes of already created PR for clean changes

**Comment by AlexYankee** [comment]
@lgordey, well, it mostly about replacing compile > optimize-chunk-asset with single emit subscription.
Will do if no fix will land in mean time.

**Comment by lgordey** [comment]
@feedm3 @AlexYankee @eilinora Try to use 2.2.0 version.
