### ISSUE TITLE
Chunk option not compatible with HMR

### ISSUE THREAD

**Issue by levrik** [mrsum/webpack-svgstore-plugin#77]
If I'm using the webpack-dev-server with HMR (hot module replacement) and this plugin with the `chunk` option a new div gets created every time I change something.
This leads to a couple of hundred SVG stores. Not critical in production but in development it slows down the browser extremely at some point.

**Comment by lgordey** [comment]
@levrik Try to use 2.2.0 version. Is it fixes this?

**Comment by levrik** [comment]
Sadly no, it not fixes it :/

**Comment by everdimension** [comment]
Isn't this a HMR problem?

**Comment by mrsum** [comment]
Try 3.0.0-beta
