### ISSUE TITLE
Define custom template

### ISSUE THREAD

**Issue by plankguy** [mrsum/webpack-svgstore-plugin#78]
Would love to be able to create my own jade template(s). Could there be an option added for that?

````
{
  ...,
  template: "./path/to/my/template.jade",
  ...
}
````

**Comment by plankguy** [comment]
#79

**Comment by plankguy** [comment]
Sweet thanks for getting on this! :smiley:

**Comment by lgordey** [comment]
No problem! 👍  Use 2.2.0 version
