### ISSUE TITLE
path.isAbsolute error

### ISSUE THREAD

**Issue by voten** [mrsum/webpack-svgstore-plugin#85]
get this issue

new to svgstore and webpack, so guess it's me :-), but don't know where to look for

Unhandled rejection TypeError: Object #<Object> has no method 'isAbsolute'
    at Compiler.<anonymous> ...node_modules\webpack-svgstore-plugin\index.js:70:25)
    at Compiler.next ....node_modules\webpack\node_modules\tapable\lib\Tapable.js:69:14)
    at ...node_modules\html-webpack-plugin\index.js:189:9
    at process._tickCallback (node.js:419:13)
From previous event:

thx for your help

**Comment by islautin** [comment]
@IvoDecae path.isAbsolute has been added to Node 0.12. There is an open PR to use polyfill for older version but you can just upgrade your Node version.

**Comment by mrsum** [comment]
fixed
