### ISSUE TITLE
When using an absolute output.publicPath, svgXHR uses a faulty path.

### ISSUE THREAD

**Issue by dmitrif** [mrsum/webpack-svgstore-plugin#86]
Given that the webpack output.publicPath is set to something like `'http://hostname:port/path/'`, and baseUrl is set to `''`, currently results in the svgXHR trying to access '/http://hostname:port/path/sprite.svg'. Instead the leading slash should only be present when a baseUrl is provided.

**Comment by dmitrif** [comment]
Getting a PR ready for this fix.

**Comment by mrsum** [comment]
in 3.0.0-beta you can override svg ajax loader with your domain name
