### ISSUE TITLE
Output SVG sprite to file system when using webpack-dev-server

### ISSUE THREAD

**Issue by shaunwest** [mrsum/webpack-svgstore-plugin#90]
I'm using webpack dev server for JS and CSS, but I'd like to output the SVG sprite generated by SvgStore to the file system. It works fine with normal webpack, but with the dev server I'm unable to find a way to do it. Is this even possible? Or does SvgStore only do in-memory output with the dev server?

**Comment by lgordey** [comment]
Yes, in webpack-dev-server mode all files are ran from memory and not copied anywhere

**Comment by shaunwest** [comment]
Would it make sense to add an option that forces SvgStore to copy files even when using the dev server? I could look into adding it myself.

**Comment by mrsum** [comment]
fixed 3.0.0-beta
