### ISSUE TITLE
Support multiple instances

### ISSUE THREAD

**Issue by jonespen** [mrsum/webpack-svgstore-plugin#92]
Is it possible to generate multiple sprite files? I'm creating a styleguide, and it would be nice to output a sprite.html (using custom `template`) with all the icons.

When trying the following code
```
plugins: [
    new SvgStorePlugin([join(src, 'icons', '**/*.svg')],
      '',
      {
        name: 'sprite.svg',
        prefix: 'icon-',
        chunk: 'app'
      }
    ),
    new SvgStorePlugin([join(src, 'icons', '**/*.svg')],
      '',
      {
        name: 'sprite.html',
        prefix: 'icon-',
        chunk: 'app'
      }
    )
  ]
```

I get the following error:
```
/Users/jon.kvisler/Sites/github/mwng/multikanal.epi7.ultra/Web/node_modules/webpack-core/lib/ConcatSource.js:24
		return typeof item === "string" ? item : item.source();
		                                             ^

TypeError: Cannot read property 'source' of undefined
    at /Users/jon.kvisler/Sites/github/mwng/multikanal.epi7.ultra/Web/node_modules/webpack-core/lib/ConcatSource.js:24:48
    at Array.map (native)
    at ConcatSource.source (/Users/jon.kvisler/Sites/github/mwng/multikanal.epi7.ultra/Web/node_modules/webpack-core/lib/ConcatSource.js:23:23)
    at Compiler.writeOut (/Users/jon.kvisler/Sites/github/mwng/multikanal.epi7.ultra/Web/node_modules/webpack/lib/Compiler.js:256:26)
    at Compiler.<anonymous> (/Users/jon.kvisler/Sites/github/mwng/multikanal.epi7.ultra/Web/node_modules/webpack/lib/Compiler.js:246:20)
    at /Users/jon.kvisler/Sites/github/mwng/multikanal.epi7.ultra/Web/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/Users/jon.kvisler/Sites/github/mwng/multikanal.epi7.ultra/Web/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/Users/jon.kvisler/Sites/github/mwng/multikanal.epi7.ultra/Web/node_modules/async/lib/async.js:209:22)
    at Compiler.emitFiles (/Users/jon.kvisler/Sites/github/mwng/multikanal.epi7.ultra/Web/node_modules/webpack/lib/Compiler.js:235:20)
    at /Users/jon.kvisler/Sites/github/mwng/multikanal.epi7.ultra/Web/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:82:15)
```

It works fine with one instance. 

Btw, great project 💯

**Comment by mrsum** [comment]
@jonespen Hello!

Can you try 3.0.0-alpha.2 version?
documentation here https://github.com/mrsum/webpack-svgstore-plugin/blob/feature/refactor/README.md

**Comment by jonespen** [comment]
Hey, thanks!

I upgraded, and it works, but I still can't figure out how to specify two different templates. AFAIK svgxhr don't take a template as parameter

**Comment by mrsum** [comment]
Hi @jonespen i don't understand what you mean about 'templates'

**Comment by mrsum** [comment]
jade/pug template for compiling data to svg, or different sprites by mask?

**Comment by mrsum** [comment]
Wherever, if you want compile 2 or more different sprites, you can use follow code
```
var __svg__ = { path: './svg/folder-1/*.svg', name: 'assets/svg/[hash].icons.svg' };
require('webpack-svgstore-plugin/src/helpers/svgxhr')(__svg__);

var __svg__ = { path: './svg/folder-2/*.svg', name: 'assets/svg/[hash].logos.svg' };
require('webpack-svgstore-plugin/src/helpers/svgxhr')(__svg__);
```

**Comment by jonespen** [comment]
Jade/pug template. If this could be customizable, I could create a html file with all the icons in the svgstore.

**Comment by mrsum** [comment]
You can set up template

```
// create svgStore instance object
    new SvgStore({
      template: 'path/to/your/pug/template.pug'
    })
```

**Comment by ephor** [comment]
> ```
var __svg__ = { path: './svg/folder-1/*.svg', name: 'assets/svg/[hash].icons.svg' };
require('webpack-svgstore-plugin/src/helpers/svgxhr')(__svg__);
```

> ```
var __svg__ = { path: './svg/folder-2/*.svg', name: 'assets/svg/[hash].logos.svg' };
require('webpack-svgstore-plugin/src/helpers/svgxhr')(__svg__);
```

Can I use something like this, but in config (not in chunk)? 

`new SvgStore(
     //=========> input path
     [
         path.join(__dirname + 'public/', 'image/svg_icons/market', '*.svg'),
         path.join(__dirname + 'public/', 'image/svg_icons/portable', '*.svg'),
     ],
     //=========> output path
     [
         path.join(__dirname + 'public/', 'image/svg_sprite/market'),
         path.join(__dirname + 'public/', 'image/svg_sprite/portable'),
     ],
     //=========> options
     {
         name: 'sprite.svg',
         chunk: 'portable.styl',
         prefix: 'svg-',
     }
)`
