### ISSUE TITLE
Long-term caching support

### ISSUE THREAD

**Issue by matpaul** [mrsum/webpack-svgstore-plugin#98]
Hello! 
Currently [hash] generated with buildTimestamp so every build time - hash change.

Could you suggest me how to implement long-term caching, i mean change hash if content change.

Thanks!

**Comment by mrsum** [comment]
Hi @matpaul thnx for issue. I'll think abt it.

**Comment by mrsum** [comment]
Yay @matpaul !
Your request has been completed.

Actual code here https://github.com/mrsum/webpack-svgstore-plugin/blob/develop/src/helpers/utils.js#L272

Try webpack-svgstore-plugin@3.0.1
If everything is okay. Plz close current issue.

**Comment by matpaul** [comment]
@mrsum thx a lot!

**Comment by fresk-nc** [comment]
any news?

**Comment by mrsum** [comment]
@fresk-nc Noup. Was so bussy. Will implemented in 3.0.5
Sorry for...

**Comment by restrry** [comment]
Guys, what is current status? as I can see last version in npm is `3.0.6`, but timestamp is still used as hash.

**Comment by asafyish** [comment]
Time based has is no good, every build will have a different hash, even with the same content.
